# Generated by Django 5.2.15 on 2026-07-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='freefire_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
