# Generated by Django 5.2.15 on 2026-07-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_freefire_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('player', 'Player'), ('admin', 'Admin'), ('owner', 'Owner')], default='player', max_length=10),
        ),
    ]
