# Generated by Django 5.2.15 on 2026-07-07 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    def set_owner(apps, schema_editor):
        User = apps.get_model('accounts', 'User')
        try:
            spidey = User.objects.get(username='spidey')
            spidey.role = 'owner'
            spidey.is_staff = True
            spidey.is_superuser = True
            spidey.save()
        except User.DoesNotExist:
            pass
        try:
            admin = User.objects.get(username='admin')
            if admin.role == 'owner':
                admin.role = 'admin'
                admin.save()
        except User.DoesNotExist:
            pass

    operations = [
        migrations.RunPython(set_owner),
    ]
