# Generated by Django 5.1.15 on 2026-07-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('solo', 'Solo'), ('duo', 'Duo'), ('squad', 'Squad')], max_length=10)),
                ('prize_pool', models.CharField(max_length=100)),
                ('entry_fee', models.PositiveIntegerField()),
                ('total_slots', models.PositiveIntegerField(default=10)),
                ('slots_filled', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='upcoming', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
